In [1]:
import pandas as pd
import numpy as np

In [12]:
df_abbe = pd.read_parquet('data_vidros/sciglass/clean/abbe_number.parquet')

In [13]:
df_abbe

,sio2,p2o5,zro2,na2o,al2o3,fe2o3,cao,mgo,k2o,b2o3,...,ni2o3,v2o3,lu2o3,hgo,tm2o3,nb2o3,tl2o3,ta2o3,tb4o7,abbe_number
id,,,,,,,,,,,,,,,,,,,,,
24800020366,69.50,0.0,0.00,0.0,0.0,0.0,0.0,0.0,7.5,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.799999
24800020367,69.50,0.0,0.00,0.0,0.0,0.0,0.0,0.0,7.5,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.900002
24800020368,69.50,0.0,0.00,0.0,0.0,0.0,0.0,0.0,7.5,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.799999
24800020369,69.50,0.0,0.00,0.0,0.0,0.0,0.0,0.0,7.5,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.900002
24800020370,69.50,0.0,0.00,0.0,0.0,0.0,0.0,0.0,7.5,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53.400002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4492600611379,0.59,0.0,7.36,0.0,0.0,0.0,0.0,0.0,0.0,52.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.610001
4492600611380,0.55,0.0,9.35,0.0,0.0,0.0,0.0,0.0,0.0,51.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.599998
4492600611381,1.62,0.0,8.29,0.0,0.0,0.0,0.0,0.0,0.0,50.78,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.580002
4492600611382,0.85,0.0,7.95,0.0,0.0,0.0,0.0,0.0,0.0,53.16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.509998
4492600611383,0.74,0.0,8.67,0.0,0.0,0.0,0.0,0.0,0.0,51.84,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.529999

In [14]:
df_t_lib = pd.read_parquet('data_vidros/sciglass/clean/t_liq.parquet')

In [15]:
df_t_lib

,sio2,p2o5,zro2,na2o,al2o3,fe2o3,cao,mgo,k2o,b2o3,...,ni2o3,v2o3,lu2o3,hgo,tm2o3,nb2o3,tl2o3,ta2o3,tb4o7,t_liq
id,,,,,,,,,,,,,,,,,,,,,
22800123528,66.63,0.0,0.000,0.0,0.00,0.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1420.0
22800123529,62.38,0.0,0.000,0.0,0.00,0.0,0.00,8.49,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1325.0
22800123530,61.80,0.0,0.000,0.0,0.00,0.0,0.00,9.68,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1310.0
22800123531,60.21,0.0,0.000,0.0,0.00,0.0,0.00,12.91,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1270.0
22800123532,59.23,0.0,0.000,0.0,0.00,0.0,0.00,14.92,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4493300611685,62.23,0.0,0.000,0.0,11.60,0.0,8.67,15.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1195.0
4493300611686,63.67,0.0,0.000,0.0,11.59,0.0,7.76,14.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1225.0
4493300611687,62.21,0.0,0.000,0.0,11.58,0.0,9.26,14.97,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1178.0
4493300611695,72.95,0.0,0.056,0.0,11.35,0.0,7.21,3.06,0.0,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1225.0
4493300611696,71.78,0.0,0.057,0.0,10.80,0.0,10.81,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1213.0

In [16]:
df_refrac = pd.read_parquet('data_vidros/sciglass/clean/refractive_index.parquet')

In [17]:
df_refrac

,sio2,p2o5,zro2,na2o,al2o3,fe2o3,cao,mgo,k2o,b2o3,...,ni2o3,v2o3,lu2o3,hgo,tm2o3,nb2o3,tl2o3,ta2o3,tb4o7,refractive_index
id,,,,,,,,,,,,,,,,,,,,,
21500020100,9.79,0.00,0.0,9.79,0.00,0.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.619
21500020101,9.49,0.00,0.0,9.49,0.00,0.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.631
21500020102,9.15,0.00,0.0,9.15,0.00,0.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.647
21500020103,10.88,0.00,0.0,10.88,0.00,0.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.658
21500020104,10.76,0.00,0.0,10.76,0.00,0.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.659
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4492700611790,72.17,0.00,0.0,10.68,9.98,0.0,4.04,3.08,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.503
4492700611791,72.41,0.00,0.0,12.62,10.00,0.0,1.97,1.98,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.500
4492700611792,72.40,0.96,0.0,12.62,9.99,0.0,0.03,2.01,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.495
4492700611793,72.37,0.01,0.0,12.62,9.98,0.0,0.03,2.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.500
4492700611794,72.32,0.01,0.0,12.68,9.99,0.0,1.97,0.05,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.503